[package]
name = "hdc1080-embedded"
version = "0.1.0"
edition = "2024"
description = "A driver library for interfacing with the HDC1080 hygrometer. Specifically targeted at embedded, no-std environments."
authors = ["Devin Lane"]

[dependencies]
embassy-time = "0.5.0"
embedded-hal-async = "1.0.0"
